name: ARM64 Assembly CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v4

      # 2. Enable ARM64 emulation
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      # 3. Enable Buildx
      - uses: docker/setup-buildx-action@v2

      # 4. Build Docker image
      - name: Build ARM64 container
        run: |
          docker build --platform=linux/arm64 -t arm64-dev .

      # 5. Run build + program in ONE container
      - name: Build and Run
        run: |
          docker run --rm --platform=linux/arm64 \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            arm64-dev \
            bash -c "make"
      
      # test cases
      - name: Tests
        run: |
          bash -c "
            echo 'Running tests' &&
            printf 'input\nLab7-1inputFile1.txt\nout.txt\ny\n'
            make run
          "

